### ISSUE TITLE
User Registration Layout

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1054]
Rework the layout of the user registration form to make it clearer the different roles for which users can register.

### TODO
- [x] *Register* and *Login* buttons in the header
- [x] Remove the *General User* and *Nat Res Mgmt Prof* links on the side of the home page 
- [x] New user registration first step dialog that describes what the user is allowed to do for each account type and the user can pick an account type
- [x] support the "affiliate" role type in the user registration dialog
- [x] remove whitespace above bullet pointed list of password rules
- [x] *I agree to the terms of use* checkbox should have an asterisk since it is required
- [x] for organization selected, change text to: *Select your organization. If your organization is not listed, then enter it in the Comment section.*
- [x] layout user details form and the Disclaimer/TOS side-by-side
- [x] remove role selector, this will be implicit based on selection in the new user registration dialog where user picks their account type
- [x] change title of user registration
- [x] make the submit button a [contained, high emphasis button](https://material.io/components/buttons#anatomy)
- [x] make text all caps as is standard for material buttons
- [x] line up form text and fields on left and right
- [x] Test on mobile screens

**Comment by machristie** [comment]
The implementation is essentially done now. The branch I've put the changes on is based on the email-verification branch so I'll wait until that one (#1049) is merged before opening up a new PR.

**Comment by machristie** [comment]
merged
