### ISSUE TITLE
In map, switch to colors that indicate animal type

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1092]
The leaflet map on the home page uses color to distinguish diagnoses types. This enhancement will switch to using color to distinguish *animal types* where animal type means a user-friendly label for a broad category of related species:
- Mammal
- Bird
- Reptile/Amphibian
- Fish
- Other

Along with this change, the legend needs to be updated and there are a few small tweaks to the legend display that will be accomplished as part of this issue.

### TODO
- [x] how to handle an event that has no species? Assuming this needs to go in Other animal type category.
- [x] make the same changes to the search results summary report
- [x] improvements to the legend - default to open, move country centroid warning to legend, etc.

**Comment by machristie** [comment]
Wireframes:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/904957/98571616-b86a5000-2282-11eb-8381-d865a250d4bb.png">

<img width="983" alt="image" src="https://user-images.githubusercontent.com/904957/98571839-f2d3ed00-2282-11eb-84ee-6f0dfe4b5104.png">

<img width="983" alt="image" src="https://user-images.githubusercontent.com/904957/98571862-f9626480-2282-11eb-980a-e39ba6492899.png">

**Comment by machristie** [comment]
A couple small things I changed that weren't in the wireframes:
- remove the `cursor: pointer` from the legend since that made the legend items appear clickable
- removed the bottom border from the legend's `.mat-expansion-panel-body`

**Comment by BlakeDraper** [comment]
Published in v2.16.0.
