### ISSUE TITLE
Simplify popup text and add map symbology

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1098]
Builds on changes in #1097 to add the symbology to the map popup and table. Simplifies the text in the popup, using hyperlinks to lead to further event details.

wireframes:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/904957/98960238-2e182b00-24d2-11eb-872e-0583c8cc939c.png">

<img width="983" alt="image" src="https://user-images.githubusercontent.com/904957/98960265-35d7cf80-24d2-11eb-8072-8808482066ec.png">

## TODO
- [x] use county name as popup title
- [x] list events at location with event details links with marker icons
- [x] in popups, use client side routing to link to event details so that app isn't reloaded
- [x] add map symbology to table
- [x] add tooltips, labels to static marker icons, such as when displayed in popup or results table

**Comment by BlakeDraper** [comment]
Published in v2.16.0.
