### ISSUE TITLE
Complete Meta Tags

### ISSUE THREAD

**Issue by mitch-wim** [USGS-WiM/whispers#370]
We need:

- [x] A short (200-character ish) description

- [x] Tags for search

- [x] Author

- [x] All favicon/icon sizes

- [x] Social Media tags & share images

We should probably have an "official" short description, since that's what will appear on Google etc.
